
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

light:
  - platform: light_control_hub
    port: /dev/ttyUSB0
    baud_rate: 115200


# light_control_hub:
#   port: "/dev/ttyUSB0"
#   baud_rate: 115200



  

